# Generated by Django 4.0.4 on 2023-04-07 09:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ServerType', models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('Pre-Production', 'Pre-Production'), ('Decommissioned', 'Decommissioned')], default='', max_length=20, null=True)),
                ('DBType', models.CharField(blank=True, choices=[('ASE', 'ASE'), ('REP', 'REP'), ('IQ', 'IQ'), ('MySQL', 'MySQL'), ('MSSQL', 'MSSQL'), ('Others', 'Others')], default='', max_length=20, null=True)),
                ('ServerName', models.CharField(blank=True, default='', max_length=120, unique=True)),
                ('DBVersion', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('HostIP', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('HostVersion', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('VIPName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Memory', models.IntegerField(blank=True, null=True)),
                ('vCPUs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SiteName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('URL_Link', models.URLField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('ServerName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('PerformedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('PerformedBy', models.CharField(blank=True, choices=[('karvinth', 'Arvinth'), ('ahegde', 'Ashik'), ('sdey', 'Saikat'), ('vsatisha', 'Vinay'), ('snegalur', 'Santosh'), ('cursu', 'Catalina'), ('jlove', 'Joe')], max_length=20, null=True)),
                ('ServerType', models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('Pre-Production', 'Pre-Production'), ('Decommissioned', 'Decommissioned')], default='', max_length=20, null=True)),
                ('Comments', ckeditor.fields.RichTextField()),
                ('EnteredBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
